import type { Metadata } from "next";
import {Outfit} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import LogContextProvider from "@/context/LogContext";

const outfit = Outfit({
  
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "FastRent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <LogContextProvider>
    <html lang="en">
      <body
        className={`${outfit} antialiased bg-[#081028]`}
      >
        {children}
      </body>
    </html>
    </LogContextProvider>
    </ClerkProvider>
  );
}
